### ISSUE TITLE
doesn't catch duplicate file names in source location

### ISSUE THREAD

**Issue by arnaudvre** [andrewning/sortphotos#82]
I've noticed that if I have many times the same file name in different subfolders, running sortphotos recursively over them only copies one even though they're different photos/videos. To work around the issue I copy all files into a staging directory so all files are in the staging directory root. Duplicate files get renamed during the copy to the staging directory. I then run my sortphotos command and now the expected number of files get copied, renamed, sorted.

**Comment by kenyob** [comment]
Is there anyone willing to program a workaround to this? How about appending the parent folder name to the exported file name. This may not mitigate all collisions of files getting the same name but may get rid of most of them. This would also be helpful because if you originally named the folder with something like a trip name or event that data would be passed into the file name making it easy to find the files you previously spent time trying to organize into non dated folders.

**Comment by SethPoulsen** [comment]
I can't replicate this problem, or find anything in the code that seems that it would cause it. Could either of you give an example of when it occurs or somewhere in the code you think may be causing the problem? Currently, the file names are iterated over starting at line 314 in /src/sortphotos.py.

**Comment by arnaudvre** [comment]
apple phones can potentially have many duplicates due to the way they name and store files in several directories. all you need to do to replicate the issue is to have a few subfolders with the same file name in them. what I noticed is that the total number of photos in the folders isn't the same as the number copied by sortphotos. using my manual workaround sortphotos copied the expected number.

**Comment by SethPoulsen** [comment]
I've tried manually naming files the same thing, and I've also tried on a set of thousands of items from an iPhone, and I still can't replicate the problem you say you have. 

How are you looking for the number of objects in the source folder? If you are doing something like right click > get info, then it is likely including all of the subfolders in the total item count, which may be why many less items than the total item count are being copied over (especially because Apple often organizes photos my moments, so there are a lot of subfolders).

**Comment by arnaudvre** [comment]
I copy the full iPhone folder hierarchy to a temp folder on my windows PC, I then search that temp folder for "*.png OR *.jpp OR *.mp4 OR *.mov" That gives me the actual number of files that needs to be copied. If I copy them manually to a second temp folder, Windows copies the expected number of files and offers to rename the ones that are duplicates. If I use sortphotos on the first temp folder only the number of files minues files that are duplicates names are copied. I had to use a bit of python scripting during troubleshooting to find out how many duplicates I had.

**Comment by andrewning** [comment]
I couldn't reproduce either.  I intentionally renamed some files to the same name to cause a collision but couldn't reproduce.  If you have a working example (and maybe info on operating system, version of python), maybe I or someone else can try again.

**Comment by arnaudvre** [comment]
I've finally managed to get my other half to let me clear all the photos on her iphone where she had been deleting selectively and re-importing the entire iphone backup every time she's upgraded her phone, this was over the course of about 10 years. Unfortunately I don't have that old structure anymore nor do I have the windows 7 installation and python environment that I thought I ran into the problem on, I'm having doubts now. I'll try to reproduce the problem every time I back up her photos going forward and will let you know if I can ever reproduce it. Thanks a lot for looking into it and for this really cool little project.
