### ISSUE TITLE
Improper Duplicate Review

### ISSUE THREAD

**Issue by Azlirn** [andrewning/sortphotos#93]
I found this out after processing about 800GB of photos. 
The script fails to compare file types will evaluating duplicate files. JPGs vs RAW formats should be treated differently. 
For example: 

If I have a file named photo-001.jpg and a file named photo-001.NEF and they are both the same photo (same creation date, taken date, etc), they should not be counted as duplicates. 

Not sure how to solve for this, but it would be cool if someone could come up with a solution.

**Comment by jdforest** [comment]
I do not observe this behavior. As far as I can tell, the code compares EXIF data --- if they are the same, it considers the files identical; however, if they are different (even the same photo with and extra tag added) the file name will be appended with a "_1".

In the example below, the two files are the corresponding raw and jpg files, but their EXIF data are not the same, so the files have the same name, except for file type.

jdforest@sorex:~/Pictures$ sortphotos --sort %Y/%m -c -r -t --rename %Y_%m%d_%H%M%S original/c/ test2/
Preprocessing with ExifTool.  May take a while for a large number of files.
    1 directories scanned
    2 image files read
[{
  "SourceFile": "original/c/XT1F1060.RAF",
  "File:FileModifyDate": "2018:04:19 12:31:26-05:00",
  "File:FileAccessDate": "2018:04:19 12:31:26-05:00",
  "File:FileInodeChangeDate": "2018:04:19 12:31:26-05:00",
  "EXIF:ModifyDate": "2017:08:16 10:31:54",
  "EXIF:DateTimeOriginal": "2017:08:16 10:31:54",
  "EXIF:CreateDate": "2017:08:16 10:31:54"
},
{
  "SourceFile": "original/c/XT1F1060.JPG",
  "File:FileModifyDate": "2018:04:19 12:31:36-05:00",
  "File:FileAccessDate": "2018:04:19 12:31:36-05:00",
  "File:FileInodeChangeDate": "2018:04:19 12:31:36-05:00",
  "EXIF:ModifyDate": "2017:08:16 10:31:54",
  "EXIF:DateTimeOriginal": "2017:08:16 10:31:54",
  "EXIF:CreateDate": "2017:08:16 10:31:54"
}]
{ready}

[1/2] (TEST - no files are being moved/copied)
Source: original/c/XT1F1060.RAF
Date/Time: 2017-08-16 10:31:54
Corresponding Tags: EXIF:DateTimeOriginal, EXIF:CreateDate, EXIF:ModifyDate
Destination (copy): test2/2017/08/2017_0816_103154.raf

[2/2] (TEST - no files are being moved/copied)
Source: original/c/XT1F1060.JPG
Date/Time: 2017-08-16 10:31:54
Corresponding Tags: EXIF:DateTimeOriginal, EXIF:CreateDate, EXIF:ModifyDate
Destination (copy): test2/2017/08/2017_0816_103154.jpg

**Comment by abondis** [comment]
not sure if this is still live but :

@Azlirn can it be that the `Source` tag in both file is the same ?

If so, I think it could be due to the use of filecmp.cmp wich only does a simple comparison instead of a full content comparison ( https://github.com/python/cpython/blob/2.7/Lib/filecmp.py#L59 )

A fix would be to further compare the files if the first `cmp` is true, but this time adding `shallow=False` so it checks the content. Another fix would be to use some hash generated based on content like md5sum/sha1sum.

**Comment by andrewning** [comment]
Extensions are already considered when comparing duplicates.  If a RAW file was left behind if must have been for some other reason (or maybe there is some other issue, I'd need to see more output info).  Currently duplicates are detected if:
1) path will be exactly the same (name and extension).
2) a stat check from filecmp is identical (stat is just a comparison of things like time of last access, time of last modification, etc.)

If you wanted to go further in duplicate detection you could pass shallow=False as @abondis suggests.  Although that shouldn't be the problem here.
