### ISSUE TITLE
This script is plain broken

### ISSUE THREAD

**Issue by brandonkal** [andrewning/sortphotos#94]
Sorting just doesn't work here's an example:
"SourceFile": "<REDACTED>/IMG_0477.JPG",
  "File:FileModifyDate": "2012:02:01 07:09:48-08:00",
  "File:FileAccessDate": "2018:02:10 12:36:58-08:00",
  "File:FileInodeChangeDate": "2018:02:08 17:15:48-08:00",
  "EXIF:ModifyDate": "2012:02:01 15:09:49",
  "EXIF:DateTimeOriginal": "2012:02:01 15:09:49",
  "EXIF:CreateDate": "2012:02:01 15:09:49"

As you can see, it appears this script is correctly identifying the photo as one taken in February. Yet here is what it does with the file:

[9/12] (TEST - no files are being moved/copied)
Source: <REDACTED>/IMG_0477.JPG
Date/Time: 2012-01-31 23:09:48
Corresponding Tags: File:FileModifyDate
Destination (move): <REDACTED>/2012/01-Jan/IMG_0477.JPG

What happened here? The script is just pulling modify dates from nowhere and sending all my photos to the wrong folder.

**Comment by brianjcohen** [comment]
This looks like a timezone conversion. The CreateDate and ModifyDate don't have a timezone offset on them, so the script must be applying one. That said, the behavior looks odd: it subtracted 16 hours and 1 second.

**Comment by eirism** [comment]
It seems like the timezone conversion is wrong in the code. From my understanding of time formats the script should do the opposite of what it is currently doing when compensating for time zones. Currently it subtracts the time zone difference from the time if the time zone is negative. https://github.com/andrewning/sortphotos/blob/master/src/sortphotos.py#L86.

The 1 second difference is because the script uses the oldest date, File:FileModifyDate in this case, and that time is 07:09:48.
